conky.config = {
    use_xft = true,
    xftalpha = 0.8,
    update_interval = 1.0,
    total_run_times = 0,
    own_window = true,
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_type = 'desktop',
    own_window_class = 'conky-journal',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    background = true,
    double_buffer = true,
    imlib_cache_size = 0,
    no_buffers = true,
    uppercase = false,
    cpu_avg_samples = 2,
    override_utf8_locale = true,

    -- placement
    alignment = 'middle_left',
    gap_x = @JOURNAL_GAP_X@,
    gap_y = 0,
    minimum_width = 590,
    maximum_width = 590,

    -- default drawing
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = false,

    -- colors
    font = 'Sarasa Mono J:size=9',
    color1 = '@COLOR1@',
    color2 = '@COLOR2@',
    color3 = '@COLOR3@',
};

conky.text = [[
${font Exo 2:size=12}${color2}Journal ${color3}${hr 1}${font}
${color1}${execi 10 journalctl -n 62 --no-pager -o cat --no-hostname -p notice | tail -n 62}
]];
