conky.config = {
    use_xft = true,
    xftalpha = 0.8,
    update_interval = 1.0,
    total_run_times = 0,
    own_window = true,
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_type = 'desktop',
    own_window_class = 'conky-time',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    background = true,
    double_buffer = true,
    no_buffers = true,
    uppercase = false,
    override_utf8_locale = true,

    -- placement
    alignment = 'middle_left',
    gap_x = @TIME_GAP_X@,
    gap_y = 0,
    minimum_width = 600,
    maximum_width = 600,

    -- default drawing
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = false,

    -- colors
    font1 = 'Exo 2:size=24',
    font2 = 'Space Mono:size=12',
    color1 = '@COLOR1@',
    color2 = '@COLOR2@',
};

conky.text = [[
${alignc}${font1}${color2}${time %H:%M}
${voffset -15}
${alignc}${if_match "${exec @GET_SINK_VOLUME@}" > "100"}${color2}${else}${color1}${endif}${execbar 6,500 @GET_SINK_VOLUME_BAR@}
${voffset 480}
${alignc}${color1}${execbar 6,500 @NVIDIA_SMI@ --query-gpu=utilization.gpu --format=csv,noheader,nounits | tr -d ' %'}
${voffset -30}
${font2}${color1}${execpi 3600 @FORMAT_CALENDAR@}
]];
